### ISSUE TITLE
Generate URL with the aswers for sharing

### ISSUE THREAD

**Issue by marcosvrs** [Dan503/Atomic-Categorizer#1]
# Use case:
One would like to share his answers for a specific component case.

# Requirements:
- At the end of the page, a share link button is shown with a link for the current form answers;
- The link must render the page with the answers selected and the total amount of recommendation points;

**Comment by Dan503** [comment]
Great idea 😁

A decent amount of work to read and write the url though ☹

Maybe with a vue routing plugin it would be easier.

I'm focused on other projects at the moment. If you create a pull request with the feature added I would be happy to accept it. 😊

I would imagine it working by modifying the url every time the user answered a question. That way you don't have to answer every question to get it working.

**Comment by Dan503** [comment]
I might give it a go over the weekend.

**Comment by Dan503** [comment]
Hi @marcosvrs,

The URL in the browser URL bar now updates with a shareable link as you answer questions.

I have created a [separate issue](https://github.com/Dan503/Atomic-Categorizer/issues/2) for the button that copies the URL to the users clipboard.

I am going to close this ticket now since the core functionality of generating a link that can be shared with colleagues is complete.

**Comment by Dan503** [comment]
Oops, I didn't test it in production. There is a bug in the url generation >_<

**Comment by Dan503** [comment]
Bug fixed now.

**Comment by marcosvrs** [comment]
Nice! Thanks! :)
